name: Test Vanishing Runner
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run it manually from the UI

jobs:
  test-k3d-runner:
    runs-on: arc-runner-set # THIS MUST MATCH your helm 'name'
    steps:
      - name: Check Environment
        run: |
          echo "Hello from the Vanishing Runner!"
          echo "I am running inside PadmaShankar's k3d cluster."
          hostname